project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Wyara Silva"
  page-navigation: true
  site-url: https://wyaravms.github.io/
  navbar:
    background: "#25384d"
    right:
      - href: index.qmd
        text: Home
      - href: home.qmd
        text: Blog
      - href: pics.qmd
        text: Photos
      - about.qmd
  page-footer: 
    left: "Website made with [Quarto](https://quarto.org/) by Wyara Silva, 2023" 
    right:
      - icon: github
        href: https://github.com/wyaravms/
      - icon: twitter
        href: https://twitter.com/wyaravms
      - icon: envelope
        href: mailto:wyaravms@gmail.com  

format:
  html: 
    theme: cosmo
    css: styles.css
    footnotes-hover: true
    toc: true
    include-after-body: ../footer.html

editor: visual

comments:
  giscus:
    repo: wyaravms/personal-blog