project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Wyara Moura"
  page-navigation: true
  site-url: https://wyaravms.github.io/
  navbar:
    background: "#264663"
    left:
      - href: index.qmd
        text: Home
      - href: home.qmd
        text: Blog
      - href: pics.qmd
        text: Photos
      - href: about.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/wyaravms
      - icon: twitter
        href: https://x.com/wyaravms
      - icon: instagram
        href: https://instagram.com/wvmouras
  page-footer: 
    left: "Website made with [Quarto](https://quarto.org/) by Wyara Moura, 2023. Hosted by [GitHub Pages](https://pages.github.com/)." 
    right:
      - icon: github
        href: https://github.com/wyaravms/
      - icon: twitter
        href: https://x.com/wyaravms
      - icon: instagram
        href: https://instagram.com/wvmouras  
      - icon: envelope
        href: mailto:wyaravms@gmail.com  

format:
  html: 
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    code-link: true

editor: visual

comments:
  giscus:
    repo: wyaravms/wyaravms.github.io