---
title: "About me"
format: html
editor: visual
params:
  solutions: false
toc: true
toc-depth: 6
toc-location: right
comments: false

---


Hi, my name is Wyara Silva, I'm a statistician, and this year I will start my doctorate in statistics at UFMG. I'm addicted to coffee, passionate about cinema and also I'm orange belt in karate. Osu.

## Education

<b> Doctoral Student in Statistics (2023-Current) </b>\
Federal University of Minas Gerais (UFMG)

<b> Master degree in Applied Mathematics and Statistics (2015-2017)</b>\
Federal University of Rio Grande do Norte (UFRN)

<b>Bachelor degree in Statistics (2010-2015)</b>\
Federal University of Piauí (UFPI)

## Published papers

<b>Moura E Silva, Wyara Vanesa</b>; Ramírez Orozco, Daniel Leonardo (2022). [Evaluación de rendimiento de los estimadores para los parámetros de la Distribución Burr XII. Comunicaciones En Estadística](https://dialnet.unirioja.es/servlet/articulo?codigo=8710099), v. 15, p. 1-14.

<b>Silva, Wyara Vanesa Moura E</b>; Nascimento, Fernando Ferraz Do; Bourguingnon, Marcelo (2020). [A change-point model for the r-largest order statistics with applications to environmental and financial data](https://doi.org/10.1016/j.apm.2020.01.064), Applied Mathematical Modelling, Volume 82, Pages 666-679, ISSN 0307-904X.

<b>E Silva, Wyara Vanesa Moura</b>; Do Nascimento, Fernando Ferraz (2019) [MCMC4Extremes: an R package for Bayesian inference for extremes and its extensions](https://doi.org/10.1080/03610918.2019.1653914), Communications in Statistics - Simulation and Computation, 51:2, 432-442.

Ferraz Do Nascimento, Fernando; <b>Moura E Silva, Wyara Vanesa</b> (2017) [A Bayesian model for multiple change point to extremes, with application to environmental and financial data](https://doi.org/10.1080/02664763.2016.1254733), Journal of Applied Statistics, 44:13, 2410-2426.

